### ISSUE TITLE
Create a gazebo environment similar to the real field!

### ISSUE THREAD

**Issue by sergimolina** [LCAS/bacchus_lcas#15]

**Comment by pulver22** [comment]
This is a first protytpe. The only thing which is pretty accurate is the ground mesh having size 33(30 at the shorter side) x 23m. The terrain is also inclined by 5 degrees and kept constant for all the mesh (this can be adjusted after reading correct terrain inclination using the onboard IMU).
I created a fence joining wood pallets but my plan is to take measurements today of 1) how many pieces of fences are for each side and 2) how tall and long each piece of the fence is. The next step is to recreate a very similar one.
![first prototype](https://i.imgur.com/7dczrmg.png)
