### ISSUE TITLE
Learn the from the data gathering team, how and which is the best approach to perform regular data collection.

### ISSUE THREAD

**Issue by sergimolina** [LCAS/bacchus_lcas#21]

**Comment by KarolineH** [comment]
The consensus seems to be that most of the procedure and data pipeline should be copied from RASberry.

Regular data collection procedure:
- Twice a week the robot is manually driven into the field
- The robot then traverses the topological map autonomously. The exact path might vary e.g. if other robots are in the field.
- Recorded data are saved along with time stamps and robot pose as well as some other robot state info 
- Precise localisation is achieved with combined RTK-GPS, wheel odometry, and pole detection. So the robot pose should be sufficient to associate data recorded in the same spot at different points in time.
- New data are saved to an SSD drive onboard and later synced to the online database while charging.

Other offline data:
- The RASberry team are also recording dates and yields of any harvest happening in-between data collection. Yields and some environmental records like temperatures are recorded offline and then manually added to the database at regular intervals.
- They record anything of interest, except irrigation records which have not been integrated yet.
